services:
  dbservice:
    image: mysql:8.0
    container_name: hirehubdb

    ports:
      - "3307:3306"

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hirehub

    volumes:
      - D:\HireHub\Database:/var/lib/mysql